name: Super Linter

on:
  push:
    branches-ignore:
      - trunk
  pull_request:

permissions:
  contents: read
  statuses: write

jobs:
  superLint:
    name: linter
    runs-on: arc-runner-large
    container:
      image: ubuntu:24.04
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: install git
        run: apt-get update && apt-get install -y git
      - name: Set Git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: stone-home/Action-Stone-DevOps/.github/actions/linter@trunk
        with:
          kubernetes-mode: true
          onepass-token: ${{ secrets.OP_ACCOUNT_TOKEN }}
          javascript: 'true'
          exclude: '(^.github/.*)'
