name: Trufflehog

on:
  push:
    branches-ignore:
      - trunk
  pull_request:

jobs:
  secretCheck:
    runs-on: arc-runner-large
    container:
      image: ubuntu:24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: stone-home/Action-Stone-DevOps/.github/actions/secret-check@trunk
